<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AddHasDebugger</name>
   <tag></tag>
   <elementGuidId>bec40464-1337-4f60-8a09-7b2a399a37f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AddHasDebugger')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium.safari&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3bb4865f-34e6-4eb0-949c-4273d8291eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/safari/AddHasDebugger.html</value>
      <webElementGuid>039d579e-6ae9-418f-b76d-0de2859fc0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.safari</value>
      <webElementGuid>d8e5a0d7-f254-4221-b74f-25182cf0e82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>cf3360b4-96ca-4bd6-9b3b-37a1f7d9bf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AddHasDebugger</value>
      <webElementGuid>ca1ed8fd-650b-4e48-ba72-9b7a521d9693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[22]/a[1]</value>
      <webElementGuid>21f8f9d1-14aa-437a-baf0-6f0741e2deda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ActiveSession/iframe_packageFrame</value>
      <webElementGuid>cf4c84ef-0853-456f-a4af-51ebb4e92a3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AddHasDebugger')]</value>
      <webElementGuid>bae0ce80-2e08-45db-b88d-495c6ede2da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasContext'])[1]/following::a[1]</value>
      <webElementGuid>3e012e62-b6ee-4f7c-9aa4-96a4e07c7b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasCdp'])[3]/following::a[2]</value>
      <webElementGuid>75e941e0-0020-4d7a-b151-5aa3b304a868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasExtensions'])[1]/preceding::a[1]</value>
      <webElementGuid>1c5657ac-8bbc-4bff-9cf5-bc8b3a868499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasFullPageScreenshot'])[1]/preceding::a[2]</value>
      <webElementGuid>5a5211c0-528e-4add-b559-69e9ba870f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AddHasDebugger']/parent::*</value>
      <webElementGuid>20decc00-f9e2-490d-9cfb-ca1684d896b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/safari/AddHasDebugger.html')]</value>
      <webElementGuid>2d53692d-fb5b-4d5b-b634-d3dbb2656eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]/a</value>
      <webElementGuid>30ad871a-0ca2-4b63-a5ce-845f14589528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/safari/AddHasDebugger.html' and @title = 'class in org.openqa.selenium.safari' and (text() = 'AddHasDebugger' or . = 'AddHasDebugger')]</value>
      <webElementGuid>fb119ff2-7d0f-457d-af37-6f38531d2f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
