<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium.chromium.ChromiumOptions</name>
   <tag></tag>
   <elementGuidId>712089e2-e2f6-4e5b-b6a2-80cb7be792eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'org.openqa.selenium.chromium.ChromiumOptions')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>932ea91f-42e1-4aa4-a030-c6eb5f4af408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../chromium/ChromiumOptions.html</value>
      <webElementGuid>2192ccb1-9c12-4f19-974a-eaf4690c3ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.chromium</value>
      <webElementGuid>5ebaa074-8ce6-4a3c-8ba3-463767494b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.chromium.ChromiumOptions</value>
      <webElementGuid>bb713ef0-834a-4ea9-b212-acc9443459a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/ul[@class=&quot;inheritance&quot;]/li[2]/ul[@class=&quot;inheritance&quot;]/li[2]/ul[@class=&quot;inheritance&quot;]/li[2]/ul[@class=&quot;inheritance&quot;]/li[1]/a[1]</value>
      <webElementGuid>294dbcbe-3bce-4034-ada9-096920bad764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium.chromium.ChromiumOptions')]</value>
      <webElementGuid>1ab3c896-9bd7-402a-be4b-fb3323dbd85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromiumOptions'])[1]/following::a[1]</value>
      <webElementGuid>52fbe44c-79a5-435e-bf76-7ff07601381a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeOptions'])[2]/preceding::a[1]</value>
      <webElementGuid>0b86c419-cfb0-4925-9b40-f76552cd4f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.chrome.ChromeOptions'])[1]/preceding::a[2]</value>
      <webElementGuid>9b05e1a4-00cd-4c9f-83a3-ad57ca36e8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium.chromium.ChromiumOptions']/parent::*</value>
      <webElementGuid>56ba2535-4edb-4df3-be2f-4d8d0f321ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../chromium/ChromiumOptions.html')])[2]</value>
      <webElementGuid>5180a7fb-086e-41fc-9feb-b1423bc5ffff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/ul/li[2]/ul/li/a</value>
      <webElementGuid>015dfcea-2eb0-4f5d-bbd1-119bf58be8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../chromium/ChromiumOptions.html' and @title = 'class in org.openqa.selenium.chromium' and (text() = 'org.openqa.selenium.chromium.ChromiumOptions' or . = 'org.openqa.selenium.chromium.ChromiumOptions')]</value>
      <webElementGuid>3f3db54f-a84d-46f8-9703-720d13a95985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
