<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ChromeOptions</name>
   <tag></tag>
   <elementGuidId>65d8a2e3-48ad-4850-be45-aec1660d4ad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ChromeOptions')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4cab57a2-56c3-4e1f-ad90-e8fbbc38e1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ChromeOptions.html</value>
      <webElementGuid>b7069b78-3f4f-475e-b8b6-71efef1800bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.chrome</value>
      <webElementGuid>2041573e-9ce3-4048-8fd0-96df9d90b703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ChromeOptions</value>
      <webElementGuid>ba82bfa4-131c-40a1-8ffc-944f689246d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/table[@class=&quot;typeSummary&quot;]/tbody[2]/tr[@class=&quot;altColor&quot;]/th[@class=&quot;colFirst&quot;]/a[1]</value>
      <webElementGuid>85d47796-af8e-4b5d-81a3-44bdbccf6620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ChromeOptions')]</value>
      <webElementGuid>3332fceb-3cc7-47dc-94b8-42ae6a25309d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeDriverService'])[2]/following::a[1]</value>
      <webElementGuid>011281f1-669d-486d-8d71-75ffbadd36df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeDriver'])[2]/preceding::a[1]</value>
      <webElementGuid>2e75eabe-0cc5-4822-8664-b941287294f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ChromeOptions']/parent::*</value>
      <webElementGuid>270d6b47-ec64-4aff-bd72-5478332ee196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ChromeOptions.html')]</value>
      <webElementGuid>60421354-1ba5-4eaa-9319-8be33dc916dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/th/a</value>
      <webElementGuid>edf6b1a7-d23c-46b3-b566-75b2cd4409aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ChromeOptions.html' and @title = 'class in org.openqa.selenium.chrome' and (text() = 'ChromeOptions' or . = 'ChromeOptions')]</value>
      <webElementGuid>0da57eb8-fa7c-49d3-8d04-a4a9e9e5d01b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
