<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AbstractHttpResponseCodec</name>
   <tag></tag>
   <elementGuidId>89a538b1-132f-48a6-92bf-db2a432a387b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AbstractHttpResponseCodec')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a5a17da-b147-4b06-832c-ff5e3ebc67ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html</value>
      <webElementGuid>42180e1d-c187-4604-8ded-58a99fc12219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.remote.codec</value>
      <webElementGuid>459bce17-7966-4221-b0ce-0bd103179259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>5ed37006-93f7-4572-97f0-69e815eb4e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AbstractHttpResponseCodec</value>
      <webElementGuid>852ded74-725b-4032-afb0-5c96909efda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[6]/a[1]</value>
      <webElementGuid>f20402c1-4380-43bf-9443-36b7a0fa0630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>0e3997af-990e-440c-86de-a33db418331e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AbstractHttpResponseCodec')]</value>
      <webElementGuid>aebe379f-31fd-45a0-ba85-60fb95f5ef49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec.CommandSpec'])[1]/following::a[1]</value>
      <webElementGuid>566ee87b-1f3d-4438-a566-b0184400dbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec'])[1]/following::a[2]</value>
      <webElementGuid>2cfb5e50-5cc3-4dd4-a8db-62eb80ac5720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractWebDriverEventListener'])[1]/preceding::a[1]</value>
      <webElementGuid>6c353c0b-e0cb-4291-9600-2b94538c19dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AcceptedW3CCapabilityKeys'])[1]/preceding::a[2]</value>
      <webElementGuid>1ad1dc3d-c42b-43c1-9856-aca7cf4386fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AbstractHttpResponseCodec']/parent::*</value>
      <webElementGuid>b25dbf8b-12b5-4f52-976a-6c7a44fba8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html')]</value>
      <webElementGuid>f71c38bd-81b9-40bc-bc32-0b2c36247f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>78efee4d-d86e-4530-bfd3-da718acf17eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html' and @title = 'class in org.openqa.selenium.remote.codec' and (text() = 'AbstractHttpResponseCodec' or . = 'AbstractHttpResponseCodec')]</value>
      <webElementGuid>25c12cdb-c7d0-427f-bcc8-32b71f812812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
