<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium.chrome</name>
   <tag></tag>
   <elementGuidId>bda7ef0a-3203-4485-97d3-47f6a495fc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='i3']/th/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i3 > th.colFirst > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>786004c1-9b4e-43a6-8e06-1faabb28f6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/chrome/package-summary.html</value>
      <webElementGuid>f713130a-70d6-4598-838f-31501787ca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.chrome</value>
      <webElementGuid>c5be6e0c-5922-4e99-8b43-eaa5a60d621c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i3&quot;)/th[@class=&quot;colFirst&quot;]/a[1]</value>
      <webElementGuid>cb4bd628-d25c-495d-b720-a33267005bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='i3']/th/a</value>
      <webElementGuid>3198c768-0407-44a8-9d46-a72f9b5ddf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium.chrome')]</value>
      <webElementGuid>90dbfa98-5662-4ed5-91d3-0d82f8940ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.bidi.log'])[1]/following::a[1]</value>
      <webElementGuid>07ae03b8-81d7-4b1f-a9a3-69aa541f0efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.bidi'])[1]/following::a[2]</value>
      <webElementGuid>a5b08cf9-cd2a-40be-8616-f596ed44c125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.chromium'])[1]/preceding::a[1]</value>
      <webElementGuid>706e9e8d-75ee-4fb5-b4d0-3f8535e34f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.cli'])[1]/preceding::a[2]</value>
      <webElementGuid>48275728-5090-451c-b247-9273fbbed3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium.chrome']/parent::*</value>
      <webElementGuid>9aaa04fa-a626-46e1-964f-27a42bb3846d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/chrome/package-summary.html')]</value>
      <webElementGuid>e7f57c06-35b2-4d11-a04e-35bd8b52127e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/th/a</value>
      <webElementGuid>5fa2a189-dfdb-403b-80cf-268332683b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/chrome/package-summary.html' and (text() = 'org.openqa.selenium.chrome' or . = 'org.openqa.selenium.chrome')]</value>
      <webElementGuid>59d117d9-845f-4a9d-a560-8755eca6f0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
