<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AdditionalHttpCommands.class</name>
   <tag></tag>
   <elementGuidId>b1af61ca-a399-48f5-955f-aa7a7a450846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AdditionalHttpCommands.class')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>pre > a[title=&quot;interface in org.openqa.selenium.remote&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>922f7efa-cb05-404b-9754-3775733d01a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../remote/AdditionalHttpCommands.html</value>
      <webElementGuid>8c3cd6e7-fc4b-49e5-8357-eec295ea0086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>interface in org.openqa.selenium.remote</value>
      <webElementGuid>3ca97705-e511-4345-a8fa-fd36af3655ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdditionalHttpCommands.class</value>
      <webElementGuid>6d41462a-699f-4500-83c0-44668b0ae2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/div[@class=&quot;description&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/pre[1]/a[1]</value>
      <webElementGuid>adc2bb0e-9a12-46a8-9446-76f2ed36787d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AddHasDebugger/iframe_classFrame</value>
      <webElementGuid>bbceef75-5595-4e04-99d7-cc5a7f8ec44c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AdditionalHttpCommands.class')]</value>
      <webElementGuid>374847b6-a81c-4d29-854c-85ac4e8d007c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HasDebugger'])[1]/following::a[1]</value>
      <webElementGuid>67aef1df-2a47-4b2f-a618-8ad2d2361be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AugmenterProvider.class'])[1]/preceding::a[1]</value>
      <webElementGuid>08a143dc-f065-4343-bced-e20878ee52d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasDebugger'])[2]/preceding::a[2]</value>
      <webElementGuid>4217dfa8-4e69-4217-a097-4eef2f27434a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AdditionalHttpCommands.class']/parent::*</value>
      <webElementGuid>05180d30-f38b-4c56-abe8-f4dde94b69bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../remote/AdditionalHttpCommands.html')])[2]</value>
      <webElementGuid>617967f8-26d3-4835-ab58-9da1b3cc130a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pre/a</value>
      <webElementGuid>321bd69f-f599-43c4-88e3-ba5a8ce18a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../remote/AdditionalHttpCommands.html' and @title = 'interface in org.openqa.selenium.remote' and (text() = 'AdditionalHttpCommands.class' or . = 'AdditionalHttpCommands.class')]</value>
      <webElementGuid>553ab446-e885-4be4-8163-75fbcb727072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
